### PR TITLE
Conform _interop to the README goal to support 2.4+.

### PR DESCRIPTION
**Pull request by jcflack**
README.rst was saying 2.4+ should be supported but some vestiges from 2.3
were in _interop.py.

http://sourceforge.net/p/pyusb/mailman/message/34078264/

### CODE REVIEW

**Comment by walac** [comment]
Since we are refactoring things, we should remove `_sorted` and `_groupby` and replace them by their builtin counterparts.

**Comment by jcflack** [comment]
I'm not sure if you get notified when I add a commit, or only when I add a comment.

So, here's a comment saying I added a commit. :)

**Comment by walac** [comment]
lgtm. Just squash both commits (`git rebase -i` and forced push do the job).

**Comment by jcflack** [comment]
Squashed.

**Comment by walac** [comment]
Merged, thanks.

**Pull request merged**
