### PR TITLE
[ADD] pyusb module to satisfy setuptools

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by rnixx** [comment]
I don't understand what this change solves. @hbrunn what's the issue here?

**Comment by hbrunn** [comment]
this solves #180 because now, we have a module with the name expected by setuptools

**Comment by rnixx** [comment]
@hbrunn sorry, that's not true. the problem in #180 was caused by #192. See https://github.com/walac/pyusb/issues/180#issuecomment-335115008

**Comment by rnixx** [comment]
@walac imho this change can be reverted, no need to import from "pyusb", which is what this change enables.

**Comment by hbrunn** [comment]
well, I don't care one way or another. This commit enabled me to just dump the url to this branch into a buildout and this works, if whatever you did has the same effect, I'm just as happy

**Comment by walac** [comment]
I merged this PR by mistake, I already reverted it but just didn't push it.

**Pull request merged**
